[package]
name = "barcode-reader-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
rxing = "0.5.7"
rxing-cli = "0.1.20"
